batch_size: 4
num_epochs: 5
input_size: 64
random_seed: 42
patience: 15
limit: 0
dataset:
  - kitti
optimizer:
  adam:
    lr: 0.01
    beta_1: 0.9
    beta_2: 0.999
    decay: 0.1
save_dir: test
save_over: True
